name: riverpod_mutation_utils_generator
description: Code generation for riverpod_mutation_utils mutation wiring.
version: 0.3.4
repository: https://github.com/pckimlong/riverpod_mutation_utils
resolution: workspace

environment:
  sdk: ^3.11.1

dependencies:
  analyzer: ^9.0.0
  build: ^4.0.0
  riverpod_mutation_utils: ^0.3.4
  riverpod_annotation: ^4.0.2
  source_gen: ^4.2.1

dev_dependencies:
  build_test: ^3.5.10
  lints: ^6.0.0
  test: ^1.25.6
